### ISSUE TITLE
some signs are left

### ISSUE THREAD

**Issue by muhiddinxon** [jomtek/AbcQuran#1]
Hello ,
i need your help
i cant find some signs in your project , in quran.com all the good , i send photo from quran.com
![2023-12-01 11 23 02](https://github.com/jomtek/AbcQuran/assets/60392078/ebcaae04-457c-4892-bd04-a894a6c9a815)

this is your screenshot 

![2023-12-01 11 28 32](https://github.com/jomtek/AbcQuran/assets/60392078/1eced9c0-d11d-4a87-a012-f8ba19a9f2f7)

this is from quran android 

![2023-12-01 11 28 38](https://github.com/jomtek/AbcQuran/assets/60392078/305f832c-9538-4f46-9eb9-7bad3cfc2b83)

plaese fix it

**Comment by muhiddinxon** [comment]
Hello , 
i fixed this issue with richtext and tap recogniser , 
thank you

**Comment by aminsedghi2** [comment]
سلام شما با دیتابیس نوشتید ؟
میشه کد را در اختیار بنده بگذارید؟
